---
  - name: Wait max 600 seconds for nodes connection
    wait_for_connection:

  - name: Centos - Install Docker
    block:
      - name: Centos - Uninstall previous docker
        yum:
          name:
            - docker
            - docker-client
            - docker-client-latest
            - docker-common
            - docker-latest
            - docker-latest-logrotate
            - docker-logrotate
            - docker-engine
          state: absent
      - name: Centos - Install docker repo
        yum_repository:
          name: docker-ce
          description: docker-ce yum repo
          baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
          gpgcheck: no
      - name: Centos - Install docker-ce
        yum:
          name:
            - docker-ce
            - docker-ce-cli
            - containerd.io
            - docker-compose-plugin
          state: present
      - name: Centos - Start docker-ce
        service:
          name: docker
          state: restarted
          enabled: true
    when: ansible_distribution == "CentOS"


  - name: Debian - Install Docker
    block:
    - name: Debian - Uninstall previous docker
      apt:
        pkg:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent
    - name: Debian - Install requirements
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - software-properties-common
    - name: Debian - Add gpg apt-key
      shell: |
        curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
        apt-key fingerprint 0EBFCD88
        exit 0
    - name: Debian - Add docker repo
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    - name: Debian - Install docker
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
    when: ansible_distribution == "Debian"

  - name: Установка pip docker
    pip:
      name: docker
      